"""Ground-truth evidence a browser-agent report is adjudicated against.

In the full pipeline this is generated by a reference (non-LLM) Playwright
script that records the real DOM state, screenshot and final URL of a frozen
fixture. For the unit benchmark the evidence is declared inline. Either way it
is deterministic: the same evidence always yields the same verdicts.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Tuple

SUCCESS = "SUCCESS"
FAILURE = "FAILURE"


@dataclass(frozen=True)
class Evidence:
    """The recorded ground truth for one task run.

    ``gold_metrics`` maps a canonical metric name to its true value:

    * ``count`` / ``price`` / ``percent`` -> ``float``
    * ``clicked`` / ``opened`` / ``typed``   -> ``str`` (action target)

    ``gold_outcome`` is ``SUCCESS`` or ``FAILURE``: what actually happened
    during the run, independently of what the agent later claims.
    """

    task_id: str
    gold_metrics: Dict[str, Any]
    gold_outcome: str = SUCCESS
    actions_allowed: Tuple[str, ...] = ()
    final_dom_hash: str = ""
    screenshot_hash: str = ""
